services:
  - type: web_service
    name: mithila-art-backend
    env: node
    region: oregon
    branch: main
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
